---
- name: "[ASKI]"
  hosts: web
  remote_user: bob

  tasks:
    - name: "[ASKI] --install prerequisites"
      become: yes
      apt:
 #        become: yes 
         name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common'] 
#        update_cache: yes
 #       name: apt-transport-https
 #       name: ca-certificates
 #      update_cache: yes 
    - name: "[ASKI] --Add Docker GPG key"
      become: yes
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: "[ASKI] --Add Docker APT repository"
      become: yes
      apt_repository:
         repo: deb [arch=amd64] https://dowload.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stab

    - name: "[ASKI] Install Docker"
      become: yes
      apt: 
        name: docker.io
#        state: latest
#        update_cache: yes  

    - name: "[ASKI] -- Copy file"
      become: yes 
      copy: 
        src: ~/monfichier.txt
        dest: /tmp/     
...
