---
- name: Install docker
  hosts: web
  remote_user: bob

  tasks:
    - name: install prerequisites
      become: yes
      apt:
 #        become: yes 
         name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common'] 
#        update_cache: yes
 #       name: apt-transport-https
 #       name: ca-certificates
 #      update_cache: yes 
    - name: Add Docker GPG key
      become: yes
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      become: yes
      apt_repository:
         repo: deb [arch=amd64] https://dowload.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stab

    - name: Install Docker
      become: yes
      apt: 
        name: docker.io
#        state: latest
#        update_cache: yes  


...
